# Generated by Django 2.0.dev20170510134720 on 2017-10-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('telefono_local', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Local')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Célular')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=80, verbose_name='Direccion')),
                ('historia', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Historia')),
                ('genero', models.CharField(max_length=10, verbose_name='Género')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cedula')),
                ('representante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Representante')),
                ('telefono_local', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Local')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Célular')),
            ],
        ),
        migrations.AddField(
            model_name='consultas',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='unidad.Pacientes'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='unidad.Pacientes'),
        ),
    ]
