# Generated by Django 2.0.dev20170510134720 on 2017-10-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0002_auto_20171029_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='unidad.Doctores'),
        ),
    ]
