# Generated by Django 2.0.dev20170510134720 on 2017-11-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0003_auto_20171029_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='historia',
            new_name='historias',
        ),
    ]
