# Generated by Django 2.0.dev20170510134720 on 2017-11-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0004_auto_20171103_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='historias',
            new_name='historia',
        ),
    ]
