# Generated by Django 2.0.dev20170510134720 on 2017-11-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0005_auto_20171103_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='hora',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Hora'),
        ),
    ]
