# Generated by Django 2.0.dev20170510134720 on 2017-11-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0007_auto_20171103_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='status',
            field=models.CharField(default='pendiente', max_length=15, verbose_name='Status'),
        ),
    ]
