# Generated by Django 2.0.dev20170510134720 on 2017-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0008_auto_20171103_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='observacion',
            field=models.CharField(default='sin observacion', max_length=80, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='diagnostico',
            field=models.CharField(default='sin diagnostico', max_length=80, verbose_name='Diagnostico'),
        ),
    ]
