# Generated by Django 2.0.dev20170510134720 on 2017-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0009_auto_20171105_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='cedula',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='edad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='diagnostico',
            field=models.CharField(blank=True, default='sin diagnostico', max_length=80, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Direccion'),
        ),
    ]
