# Generated by Django 2.0.dev20170510134720 on 2017-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0010_auto_20171105_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cédula'),
        ),
    ]
