# Generated by Django 2.0.dev20170510134720 on 2017-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0011_pacientes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Diagnostico'),
        ),
    ]
